name: Build

on:
  push:
    branches:
      - build-test

jobs:
  build:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        node-version: [18.x]
    env: 
      WPGRAPHQL_URL: ${{secrets.WPGRAPHQL_URL}}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build